language: python

service: docker

dist: xenial

branches:
  only:
    - master
    - "/^release-[0-9]+\\..*$/"

# before_install:
#   - sudo apt-get update
#   - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#   - bash miniconda.sh -b -p $HOME/miniconda
#   - export PATH="$HOME/miniconda/bin:$PATH"
#   - hash -r
#   - conda config --set always_yes yes --set changeps1 no
#   # Useful for debugging any issues with conda
#   - conda info -a

#   - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch scipy -c pytorch-nightly
#   - source activate test-environment
#   - |
#     if [[ "$IMAGE_BACKEND" == "Pillow-SIMD" ]]; then
#       pip uninstall -y pillow && CC="cc -march=native" pip install --force-reinstall pillow-simd
#     fi
#   - pip install future
#   - pip install pytest pytest-cov codecov
#   - pip install typing
#   - |
#     if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
#       pip install -q --user typing-extensions==3.6.6
#       pip install -q --user -i https://test.pypi.org/simple/ ort-nightly==1.3.0.dev202005123
#     fi
#   - conda install av -c conda-forge


install:
  - make imagenet

stages:
  - build
  - push

jobs:
  include:
    - stage: build
      name: build
      python: "3.6"
      # env: IMAGE_BACKEND=Pillow-SIMD
      script: |
        make build
        make run
        sleep 10
        make test
    - stage: push
      name: push
      if: type = push AND branch =~ /^master$/
      script: |
        make build
        make push

after_success:
  # Necessary to run coverage combine to rewrite paths from
  # /travis/env/path/site-packages/torchvision to actual path
  - coverage combine .coverage
  - coverage report
  - codecov
