---
apiVersion: v1
kind: Namespace
metadata:
  name: image-classifier
  labels:
    name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: image-classifier
  labels:
    app: image-classifier
  name: image-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classifier
  template:
    metadata:
      labels:
        app: image-classifier
    spec: 
      containers:
      - image: quay.io/cdoan0/pytorch-imageclassifier:latest
        imagePullPolicy: Always
        name: image-classifier
---
apiVersion: v1
kind: Service
metadata:
  namespace: image-classifier
  labels:
    app: image-classifier
  name: image-classifier
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: image-classifier
  # type: LoadBalancer
